# Generated by Django 5.1.6 on 2025-03-04 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userLogin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='asdf@gmail.com', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='mobile',
            field=models.CharField(default='asdf', max_length=10),
            preserve_default=False,
        ),
    ]
